name: addnoise tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/addnoise/**'
      - '!**.md'
  pull_request:
    paths:
      - 'infrastructure/addnoise/**'
      - '!**.md'

jobs:
  tests:
    name: Run pytests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/addnoise

    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pandas h5py scipy nibabel more_itertools tqdm --quiet
      
      - name: Run tests
        run: pytest test_addnoise.py -v -s
