name: Apptainer Build Push

on:
  push:
    tags:
      - '*'           # Push events to every tag not containing /
 
jobs:
  build-download:
    name: Download containers

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lowercase namespace    # see https://github.com/orgs/community/discussions/25768
        run: |
          echo "NAMESPACE=$( echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]' )" >> "${GITHUB_ENV}"

      - name: Build containers
        run: |
          echo Building usecase 2.1; cd ${GITHUB_WORKSPACE}/usecase-2.1 && apptainer build download.sif download.def
          echo Building usecase 2.2; cd ${GITHUB_WORKSPACE}/usecase-2.2 && apptainer build download.sif download.def
          echo Building usecase 2.3; cd ${GITHUB_WORKSPACE}/usecase-2.3 && apptainer build download.sif download.def
          echo Building usecase 2.4; cd ${GITHUB_WORKSPACE}/usecase-2.4 && apptainer build download.sif download.def
          echo Building usecase 2.5; cd ${GITHUB_WORKSPACE}/usecase-2.5 && apptainer build download.sif download.def

      - name: Login and push containers
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.1/download.sif oras://ghcr.io/${NAMESPACE}/download-2.1.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.1/download.sif oras://ghcr.io/${NAMESPACE}/download-2.1.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.2/download.sif oras://ghcr.io/${NAMESPACE}/download-2.2.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.2/download.sif oras://ghcr.io/${NAMESPACE}/download-2.2.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.3/download.sif oras://ghcr.io/${NAMESPACE}/download-2.3.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.3/download.sif oras://ghcr.io/${NAMESPACE}/download-2.3.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.4/download.sif oras://ghcr.io/${NAMESPACE}/download-2.4.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.4/download.sif oras://ghcr.io/${NAMESPACE}/download-2.4.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.5/download.sif oras://ghcr.io/${NAMESPACE}/download-2.5.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/usecase-2.5/download.sif oras://ghcr.io/${NAMESPACE}/download-2.5.sif:latest

  build-pipeline-2-1:
    name: Pipeline 2.1
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lowercase namespace    # see https://github.com/orgs/community/discussions/25768
        run: |
          echo "NAMESPACE=$( echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]' )" >> "${GITHUB_ENV}"

      - name: Build pipeline container
        run: |
          cd ${GITHUB_WORKSPACE}/usecase-2.1 && apptainer build pipeline.sif pipeline-r.def  # there are also container definition files for the same pipeline based on MATLAB, Python, and Julia

      - name: Login and push container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push usecase-2.1/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.1.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.1/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.1.sif:latest

  build-pipeline-2-3:
    name: Pipeline 2.3
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lowercase namespace    # see https://github.com/orgs/community/discussions/25768
        run: |
          echo "NAMESPACE=$( echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]' )" >> "${GITHUB_ENV}"

      - name: Build pipeline container
        run: |
          cd ${GITHUB_WORKSPACE}/usecase-2.3 && apptainer build pipeline.sif pipeline.def

      - name: Login and push container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push usecase-2.3/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.3.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.3/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.3.sif:latest

  build-pipeline-2-4:
    name: Pipeline 2.4

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lowercase namespace    # see https://github.com/orgs/community/discussions/25768
        run: |
          echo "NAMESPACE=$( echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]' )" >> "${GITHUB_ENV}"

      - name: Build pipeline container
        run: |
          cd ${GITHUB_WORKSPACE}/usecase-2.4 && apptainer build pipeline.sif pipeline.def

      - name: Login and push container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push usecase-2.4/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.4.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.4/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.4.sif:latest

  build-pipeline-2-5:
    name: Pipeline 2.5
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lowercase namespace    # see https://github.com/orgs/community/discussions/25768
        run: |
          echo "NAMESPACE=$( echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]' )" >> "${GITHUB_ENV}"

      - name: Build pipeline container
        run: |
          cd ${GITHUB_WORKSPACE}/usecase-2.5 && apptainer build pipeline.sif pipeline.def

      - name: Login and push container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push usecase-2.5/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.5.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.5/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.5.sif:latest

  build-pipeline-2-6:
    name: Pipeline 2.6
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lowercase namespace    # see https://github.com/orgs/community/discussions/25768
        run: |
          echo "NAMESPACE=$( echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]' )" >> "${GITHUB_ENV}"

      - name: Build pipeline container
        run: |
          cd ${GITHUB_WORKSPACE}/usecase-2.6 && apptainer build pipeline.sif pipeline.def

      - name: Login and push container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push usecase-2.6/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.6.sif:${GITHUB_REF_NAME}
          apptainer push usecase-2.6/pipeline.sif oras://ghcr.io/${NAMESPACE}/pipeline-2.6.sif:latest

  build-infrastructure:
    name: Infrastructure containers

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lowercase namespace    # see https://github.com/orgs/community/discussions/25768
        run: |
          echo "NAMESPACE=$( echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]' )" >> "${GITHUB_ENV}"

      - name: Build containers
        run: |
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build scramble.sif         scramble.def
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build privacy.sif          privacy.def
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build singlesubject.sif    singlesubject.def
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build leaveoneout.sif      leaveoneout.def
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build cleanup.sif          cleanup.def
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build mergesubjects.sif    mergesubjects.def
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build mergegroup.sif       mergegroup.def
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build calibratenoise.sif   calibratenoise.def
          cd ${GITHUB_WORKSPACE}/infrastructure && apptainer build addnoise.sif         addnoise.def

      - name: Login and push containers
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/scramble.sif         oras://ghcr.io/${NAMESPACE}/scramble.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/scramble.sif         oras://ghcr.io/${NAMESPACE}/scramble.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/privacy.sif          oras://ghcr.io/${NAMESPACE}/privacy.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/privacy.sif          oras://ghcr.io/${NAMESPACE}/privacy.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/singlesubject.sif    oras://ghcr.io/${NAMESPACE}/singlesubject.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/singlesubject.sif    oras://ghcr.io/${NAMESPACE}/singlesubject.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/leaveoneout.sif      oras://ghcr.io/${NAMESPACE}/leaveoneout.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/leaveoneout.sif      oras://ghcr.io/${NAMESPACE}/leaveoneout.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/cleanup.sif          oras://ghcr.io/${NAMESPACE}/cleanup.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/cleanup.sif          oras://ghcr.io/${NAMESPACE}/cleanup.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/mergesubjects.sif    oras://ghcr.io/${NAMESPACE}/mergesubjects.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/mergesubjects.sif    oras://ghcr.io/${NAMESPACE}/mergesubjects.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/mergegroup.sif       oras://ghcr.io/${NAMESPACE}/mergegroup.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/mergegroup.sif       oras://ghcr.io/${NAMESPACE}/mergegroup.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/calibratenoise.sif   oras://ghcr.io/${NAMESPACE}/calibratenoise.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/calibratenoise.sif   oras://ghcr.io/${NAMESPACE}/calibratenoise.sif:latest
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/addnoise.sif         oras://ghcr.io/${NAMESPACE}/addnoise.sif:${GITHUB_REF_NAME}
          apptainer push ${GITHUB_WORKSPACE}/infrastructure/addnoise.sif         oras://ghcr.io/${NAMESPACE}/addnoise.sif:latest
