name: calibratenoise tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/calibratenoise/**'
      - '!**.md'
  pull_request:
    paths:
      - 'infrastructure/calibratenoise/**'
      - '!**.md'

jobs:
  tests:
    name: Run pytests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/calibratenoise

    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
      
      - name: Run tests
        run: pytest test_calibratenoise.py -v -s
